[package]
name = "bench"
version = "0.1.0"
authors = ["Bingus <shankern@protonmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["canvas", "tokio", "debug", "glow"] }
rand = "0.8.5"

[features]
gradient = []